FILE fqName:<root> fileName:/tryCatch.kt
  FUN #0 name:test1 visibility:public modality:FINAL <> () returnType:kotlin.Unit 
    BLOCK_BODY
      TRY type=IrErrorType
        try: CALL '#1 public final fun println (): kotlin.Unit [inline] declared in kotlin.io' type=kotlin.Unit origin=null
        CATCH parameter=#2 val e: kotlin.Throwable [val] declared in <root>.test1
          VAR #2 name:e type:kotlin.Throwable [val] 
          CALL '#1 public final fun println (): kotlin.Unit [inline] declared in kotlin.io' type=kotlin.Unit origin=null
        finally: CALL '#1 public final fun println (): kotlin.Unit [inline] declared in kotlin.io' type=kotlin.Unit origin=null
  FUN #3 name:test2 visibility:public modality:FINAL <> () returnType:kotlin.Int 
    BLOCK_BODY
      RETURN type=kotlin.Nothing from='#3 public final fun test2 (): kotlin.Int declared in <root>'
        TRY type=IrErrorType
          try: BLOCK type=kotlin.Int origin=null
            CALL '#1 public final fun println (): kotlin.Unit [inline] declared in kotlin.io' type=kotlin.Unit origin=null
            CONST Int type=kotlin.Int value=42
          CATCH parameter=#4 val e: kotlin.Throwable [val] declared in <root>.test2
            VAR #4 name:e type:kotlin.Throwable [val] 
            BLOCK type=kotlin.Int origin=null
              CALL '#1 public final fun println (): kotlin.Unit [inline] declared in kotlin.io' type=kotlin.Unit origin=null
              CONST Int type=kotlin.Int value=24
          finally: BLOCK type=kotlin.Int origin=null
            CALL '#1 public final fun println (): kotlin.Unit [inline] declared in kotlin.io' type=kotlin.Unit origin=null
            CONST Int type=kotlin.Int value=555
